% In this file, we write the data generated by CK-Means to the file(s).
% By Yingfan LIU, Mar. 19, 2015


function write_to_file(fn, codes)
codes = codes - 1;
fid = fopen(fn, 'wb');
[n,d] = size(codes);
data = [(0:n-1)' codes];
data = data';
fwrite(fid, data, 'int32');
fclose(fid);